StateManagement/Models/ErrorViewModel.cs
namespace StateManagement.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

StateManagement/Models/User.cs
namespace StateManagement.Models
{
    public class User
    {
        public int UserID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    }
}

StateManagement/Controllers/CookieController.cs
using Microsoft.AspNetCore.Mvc;

namespace StateManagement.Controllers
{
    public class CookieController : Controller
    {
        public IActionResult Index()
        {
            // HttpContext http üzerindeki yapılara erişmemi sağlar. Response/Request olaya göre
            // Cookies bir collection
            // Kullanıcı izin verirse bu dataları kullanıcıya özel temp folder'da saklar
            HttpContext.Response.Cookies.Append("AppName", "Contoso"); // key value
            HttpContext.Response.Cookies.Append("PersonName", "John Doe");
            HttpContext.Response.Cookies.Append("PersonAge", "30"); 
            HttpContext.Response.Cookies.Append("PersonMail", "johndoe@contoso.com");
            HttpContext.Response.Cookies.Append("Role", "User"); 
            return View();
        }

        public IActionResult ShowCookie()
        {
            ViewBag.AppName = GetCookieVal("AppName");
            ViewBag.PersonName = GetCookieVal("PersonName");
            ViewBag.PersonAge = GetCookieVal("PersonAge");
            ViewBag.PersonMail = GetCookieVal("PersonMail");
            ViewBag.Role = GetCookieVal("Role");
            return View();
		}

		private string GetCookieVal(string key) // key: AppName, PersonName...
		{
            // Kullanıcının makineden bir şey okuyabilmem için Request
            HttpContext.Request.Cookies.TryGetValue(key, out string cookieValue);
            return cookieValue;
		}
	}
}

StateManagement/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using StateManagement.Models;

namespace StateManagement.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            HttpContext.Session.Clear();
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

StateManagement/Controllers/QueryStringController.cs
using Microsoft.AspNetCore.Mvc;
using StateManagement.Models;

namespace StateManagement.Controllers
{
	public class QueryStringController : Controller
	{
		public IActionResult Index(int userID, string username, string password)
		{
			User user = new User()
			{
				UserID = userID,
				Username = username,
				Password = password
			};
			return View(user);
		}

 		// Query string nesneleri context'te de taşınıyor
		public IActionResult QueryStringDetails()
		{
			int userID = int.Parse(HttpContext.Request.Query["userID"].ToString());
            string username = HttpContext.Request.Query["username"].ToString();
            string password = HttpContext.Request.Query["password"].ToString();

            User user = new User()
            {
                UserID = userID,
                Username = username,
                Password = password
            };

			return View(user);
        } 
	}
}

StateManagement/Controllers/SessionController.cs
using Microsoft.AspNetCore.Mvc;

namespace StateManagement.Controllers
{
    public class SessionController : Controller
    {
        public IActionResult Index()
        {
            HttpContext.Session.SetString("AppName", "Contoso");
            HttpContext.Session.SetString("PersonName", "John Doe");
            HttpContext.Session.SetInt32("PersonAge", 30);
            HttpContext.Session.SetString("PersonEmail", "johndoe@contoso.com");
            HttpContext.Session.SetString("Role", "User");
            return View();
        }
        public IActionResult ShowSession()
        {
            ViewBag.AppName = HttpContext.Session.GetString("AppName");
            ViewBag.PersonName = HttpContext.Session.GetString("PersonName");
            ViewBag.PersonAge = HttpContext.Session.GetInt32("PersonAge");
            ViewBag.PersonEmail = HttpContext.Session.GetString("PersonEmail");
            ViewBag.Role = HttpContext.Session.GetString("Role");

            return View();
		}
    }
}

StateManagement/Views/Cookie/Index.cshtml
@{
	ViewData["Title"] = "Cookie | Index";
}

<div class="card">
	<div class="card-header">
		<h1 class="bg-info text-white">Cookie Index</h1>
	</div>
	<div class="card-body">
		Cookie has been created! Visit cookie page to see results.
	</div>
	<br />
	<br />
	<a class="btn btn-success" asp-action="ShowCookie" asp-controller="Cookie">See Cookies</a>
</div>

StateManagement/Views/Cookie/ShowCookie.cshtml
@{
	ViewData["Title"] = "Show Cookie Information";
}

<div class="row justify-content-lg-center">
	<div class="card">
		<div class="card-header">
			<h3 class="bg-info text-danger">~ Cookie Information ~</h3>
		</div>
		<div class="card-body">
			<ul class="list-group">
				<li class="list-group-item">Company Name: @ViewBag.AppName</li>
				<li class="list-group-item">Person Name: @ViewBag.PersonName</li>
				<li class="list-group-item">Person Age: @ViewBag.PersonAge</li>
				<li class="list-group-item">Person Mail: @ViewBag.PersonMail</li>
				<li class="list-group-item">Person Role: @ViewBag.Role</li>
			</ul>
		</div>
		<div class="card-footer">
			<a class="btn btn-warning btn-block" asp-action="Index" asp-controller="Cookie">Go back</a>
		</div>
	</div>
</div>

StateManagement/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

StateManagement/Views/QueryString/Index.cshtml
@model StateManagement.Models.User

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<div>
    <h4>User</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Username)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Username)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

StateManagement/Views/QueryString/QueryStringDetails.cshtml
@model StateManagement.Models.User

@{
    ViewData["Title"] = "QueryStringDetails";
}

<h1>QueryStringDetails</h1>

<div>
    <h4>User</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Username)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Username)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

StateManagement/Views/Session/Index.cshtml
@{
	ViewData["Title"] = "Session | Index";
}

<div class="card">
	<div class="card-header">
		<h1 class="bg-info text-white">Session Index</h1>
	</div>
	<div class="card-body">
		Session has been created! Visit Session page to see results.
	</div>
	<br />
	<br />
	<a class="btn btn-success" asp-action="ShowSession" asp-controller="Session">See Session</a>
</div>

StateManagement/Views/Session/ShowSession.cshtml
@{
	ViewData["Title"] = "Show Session Information";
}

<div class="row justify-content-lg-center">
	<div class="card">
		<div class="card-header">
			<h3 class="bg-info text-danger">~ Session Information ~</h3>
		</div>
		<div class="card-body">
			<ul class="list-group">
				<li class="list-group-item">Company Name: @ViewBag.AppName</li>
				<li class="list-group-item">Person Name: @ViewBag.PersonName</li>
				<li class="list-group-item">Person Age: @ViewBag.PersonAge</li>
				<li class="list-group-item">Person Email: @ViewBag.PersonEmail</li>
				<li class="list-group-item">Person Role: @ViewBag.Role</li>
			</ul>
		</div>
		<div class="card-footer">
			<a class="btn btn-warning btn-block" asp-action="Index" asp-controller="Session">Go back</a>
		</div>
	</div>
</div>

StateManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StateManagement</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/StateManagement.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">StateManagement</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cookie" asp-action="Index">Cookie Index</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Session" asp-action="Index">Session Index</a>
                        </li>
                        <li class="nav-item">
                            @* <a class="nav-link text-dark" asp-area="" asp-controller="QueryString" asp-action="Index/?UserID=1&Username=johndoe&Password=123">Query String Index</a> *@
                            <a class="nav-link text-dark" href="QueryString/Index/?UserID=1&Username=johndoe&Password=123">Query String Index</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" href="QueryString/QueryStringDetails/Index/?UserID=1&Username=johndoe&Password=123">Query String Details Index</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - StateManagement - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>